name: build
on: [push]
jobs:
  codecov:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            $GOCACHE
            $GOPATH/pkg/mod
          key: |
            ${{ runner.os }}-build-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/go.mod') }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: test
        run: |
          echo $GOCACHE
          ls $GOPATH/pkg/mod
      - name: build
        run: |
          go build
